[package]
name = "protobuf-test-common"
version = "0.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
publish = false
edition = "2021"
description = """
Common code of protobuf tests
"""

[lib]
doctest = false
bench = false

[features]
default = []
proto3 = []
with-bytes = ["bytes", "protobuf/with-bytes"]

[dependencies]
anyhow    = "1.0.53"
glob         = "0.2"
log          = "0.4"
env_logger   = "0.5.*"
tempfile     = "3.0"
bytes = { version = "1.1", optional = true }

protobuf = { path = "../../protobuf" }
protobuf-json-mapping = { path = "../../protobuf-json-mapping" }
protobuf-codegen = { path = "../../protobuf-codegen" }
